
## NumPy Quick Review



In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([1,2,3])
print(A)

[1 2 3]


In [4]:
np.shape(A)

(3,)

In [5]:
np.size(A)

3

In [7]:
B = np.arange(1,13)
print(B)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
B.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
B = B.reshape(3,4)
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Matrix product

Both of these two notations yield the same result

A @ B

A.dot(B)

In [15]:
# Matrix Product
C = A @ B
print(C)

[38 44 50 56]


In [16]:
D = A.dot(B)
print(D)

[38 44 50 56]


In [26]:
X = np.arange(1,13).reshape(6,2)
print(X)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [27]:
Y = np.arange(11,23).reshape(6,2)
print(Y)

[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]]


In [31]:
Z = X.dot(Y.T)
print(Z)

[[ 35  41  47  53  59  65]
 [ 81  95 109 123 137 151]
 [127 149 171 193 215 237]
 [173 203 233 263 293 323]
 [219 257 295 333 371 409]
 [265 311 357 403 449 495]]


Element-wise Addition

In [17]:
A = np.arange(1,13).reshape(6,2)
print(A)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [18]:
B = np.arange(11,23).reshape(6,2)
print(B)

[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]]


In [19]:
print(A+B)

[[12 14]
 [16 18]
 [20 22]
 [24 26]
 [28 30]
 [32 34]]


Element-wise Multiplication

In [20]:
print(A*B)

[[ 11  24]
 [ 39  56]
 [ 75  96]
 [119 144]
 [171 200]
 [231 264]]


## Matrix Operations

In [34]:
A = np.array([1,2,3])
B = np.arange(1,13).reshape(3,4)
C = np.ones((2,3))
D = np.eye(3)
E = np.zeros((2,3))

In [35]:
print(A)
print(B)
print(C)
print(D)
print(E)

[1 2 3]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [36]:
# 2A + 1

print(2*A+1)

[3 5 7]


In [38]:
# Sum of the rows of B

print(B.sum(axis=1))

[10 26 42]


In [39]:
# Sum of the columns of B

print(B.sum(axis=0))

[15 18 21 24]


In [41]:
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
# Number of elements of B greater than 5

print(B[B>5].size)

7


In [51]:
# C + C

print(C+C)

[[2. 2. 2.]
 [2. 2. 2.]]


In [53]:
# A @ B

print(A@B)

[38 44 50 56]


In [55]:
print((B@B.T)-D)

[[ 29.  70. 110.]
 [ 70. 173. 278.]
 [110. 278. 445.]]
